# 需要手动创建ectd的certs；执行etcd-certs.sh中的命令
#
namespace: kube-devops
resources:
  - "kube-state-metrics-2.6.0"
  - configmap.yaml
  - "prometheus-pv.yaml"
  - "rbac.yaml"
  - service.yaml
  - statefulsets.yaml
  - ingress.yaml
  - grafana
patchesJson6902:
  - target:
      kind: "PersistentVolume"
      version: "v1"
      group: ""
      name: prometheus-lpv-0
    path: edit.yaml
